language: go

go_import_path: github.com/aws/aws-xray-sdk-go

sudo: required

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11" 
  - "1.12"
  - "tip"

env:
  - DEP_VERSION="0.5.1"
  - GO111MODULE=on

before_install:
  - if [ $TRAVIS_GO_VERSION == "1.9" ] ||
    [ $TRAVIS_GO_VERSION == "1.10" ]; then
      # https://golang.github.io/dep/docs/FAQ.html#how-do-i-use-dep-in-ci
      # Download the binary to bin folder in $GOPATH
      curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep;
      # Make the binary executable
      - chmod +x $GOPATH/bin/dep
    fi

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 67790b3dbede72cfdc54aa53be4706322c9499e0 && go install && cd -
  - echo $TRAVIS_GO_VERSION
  - if [ $TRAVIS_GO_VERSION == "1.7" ] ||
    [ $TRAVIS_GO_VERSION == "1.8" ]; then
      glide install;
    elif [ $TRAVIS_GO_VERSION == "1.9" ] ||
    [ $TRAVIS_GO_VERSION == "1.10" ]; then
      dep ensure;
    else
      go get;
    fi

script:
  - make test

matrix:
  allow_failures:
    - go: tip
    - go: "1.7"
    - go: "1.8"