language: go

go_import_path: github.com/aws/aws-xray-sdk-go

sudo: required

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11" 
  - "1.12"
  - "tip"

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 67790b3dbede72cfdc54aa53be4706322c9499e0 && go install && cd -
  - if [ $TRAVIS_GO_VERSION == "1.7.x" ] ||
    [ $TRAVIS_GO_VERSION == "1.8.x" ]; then
      glide install;
    elif [ $TRAVIS_GO_VERSION == "1.9.x" ] ||
    [ $TRAVIS_GO_VERSION == "1.10.x"]; then
      dep ensure;
    else
      env GO111MODULE=on go get;
    fi

script:
  - make test

matrix:
  allow_failures:
    - go: tip
    - go: "1.7"
    - go: "1.8"